### ISSUE TITLE
Pdf preview does not show and close properly in Firefox 

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#41]
![screenshot from 2017-12-25 16-59-22](https://user-images.githubusercontent.com/26770254/34341306-7b0121a4-e995-11e7-9150-7be8853b9f87.png)
There is no margin under the preview. This may not be a big problem, as it is possible to scroll down and I only miss the most down part of the pdf that nay way does not contain text.
A bigger issue: When I click outside of the pdf it does not close and I can not find any other way to close it.

![screenshot from 2017-12-25 17-07-08](https://user-images.githubusercontent.com/26770254/34341362-4829dbd0-e996-11e7-8f6b-07678d166222.png)

The first problem of not showing correctly I also have when in Chromium. Over there it does close properly.

**Comment by mani47** [comment]
fixed in 2f76293
