### ISSUE TITLE
Specific titles for pdf's?

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#43]
When a pdf is created now the name is just "download-x". Could this also be a name that is more connected to the content? Like: "Access Request ABN" or " Reminder ING?"
![screenshot from 2017-12-26 12-41-01](https://user-images.githubusercontent.com/26770254/34356784-45aca030-ea41-11e7-98af-016b5812100a.png)

**Comment by mani47** [comment]
Fixed in latest release.
