### ISSUE TITLE
Adding a 2nd Reminder Template

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#44]
We need a 2nd reminder template. This 2nd reminder should be in the workflow after the 1st reminder in case after a certain time (e.g 14days) an answer is still not received. 

If the 2nd reminder Template is added on the back end let me know and I will add the template versions in both English and Dutch.

**Comment by mani47** [comment]
Added to template_types, When you define a new template you can choose type 'second reminder' now.
