### ISSUE TITLE
Being able to go back after a certain action

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#45]
For a variety of reasons it may be necessary to go a step back in the workflow. 
Example: After having created a access request letter, I get 2 options when I want to update my status. 1. I sent the access request
2. I don't want to send the access request
but there should also be
3. I want to go back and change the access request

![screenshot from 2017-12-26 13-45-22](https://user-images.githubusercontent.com/26770254/34356976-1b336422-ea43-11e7-8c0b-8daca46c68ee.png)

**Comment by mani47** [comment]
Implemented undo, edit letter, attachment, edit remarks for last state in #64
