### ISSUE TITLE
Integrate Dutch translations of Access Request letter and reminder 

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#46]
I added the reminder letter template as well as the Dutch translations for the request letter and the reminder through the admin panel. They now need to be integrated into the platform but I do not know how.

**Comment by mani47** [comment]
Rene, you should use ISO 639-1 2 letter code, I changed the defined language on the template to "nl". we should use "en' and "nl". we also need to translate all the file with ".en" extension here: https://github.com/DataRights/MAPPED/tree/develop/config/locales to ".nl"

**Comment by Beltrandroid** [comment]
Dutch and plenty of other translations of devise.en.yml here:

https://github.com/plataformatec/devise/wiki/I18n

**Comment by mani47** [comment]
Thanks @Beltrandroid I integrated devise official translations, we still need other translations specially for en.yml file.

**Comment by Rene-Mahieu** [comment]
Hi  @mani47 , I translated the en.yml to Dutch and rewrote the nl.yml accordingly.
I also found a translation for rails_admin.en.yml --> rails_admin.nl.yml here: https://gist.github.com/DRiKE/1909240 however it seems that it has some extra lines and some of the lines that our file has are missing. Is it still useful? Anyway, I do not think the admin side of the project has to be translated.

**Comment by mani47** [comment]
Hi @Rene-Mahieu Thanks, About rails_admin link I will use it, where is the nl.yml file you translated?

**Comment by Rene-Mahieu** [comment]
Hi, I tried to upload the file and pull it. It seems that I made a mistake in that, because the system said there was an error in building. Maybe you can tell me what I did wrong? In any case here is the file: 
[nl.txt](https://github.com/DataRights/MAPPED/files/1695776/nl.txt)

**Comment by mani47** [comment]
Yeah I saw that, It's uploaded now and you can see it on live website.
