### ISSUE TITLE
New access request letter does not show postal codes of participant nor organization. Also does not show the organisation name.

### ISSUE THREAD

**Issue by Rene-Mahieu** [DataRights/MAPPED#95]
![screenshot from 2018-02-06 17-11-47](https://user-images.githubusercontent.com/26770254/35870197-57ece674-0b61-11e8-9557-d1a66fcccefb.png)
I just created a new Sector and a new organisation and added them to the Starter Kit campaign. Happy that this went smoothly. However if I am now making a new access request letter postal codes do not show on the letter (also not for the organisations that were already in the database.) Also the organisation name is not shown at the top of the address.

**Comment by mani47** [comment]
It's because of template not conforming to LIQUID template format, for any liquid tag template should use { instead of [.

<img width="430" alt="screen shot 2018-02-08 at 4 31 36 pm" src="https://user-images.githubusercontent.com/6079041/35973087-8eb5dc64-0ced-11e8-9b1c-ad4ea3f301a0.png">
